// source: tests/proto/repeatedPrimitives.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.repeatedFields_, null);
};
goog.inherits(proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.displayName = 'proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.repeatedFields_ = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.toObject = function(opt_includeInstance) {
  return proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.toObject = function(includeInstance, msg) {
  var f, obj = {
    doubleFieldList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    floatFieldList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    int32FieldList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    int64FieldList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    uint32FieldList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    uint64FieldList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    sint32FieldList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    sint64FieldList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    fixed32FieldList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    fixed64FieldList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    sfixed32FieldList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    sfixed64FieldList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    boolFieldList: (f = jspb.Message.getRepeatedBooleanField(msg, 13)) == null ? undefined : f,
    stringFieldList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    bytesFieldList: msg.getBytesFieldList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest;
  return proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setDoubleFieldList(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setFloatFieldList(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setInt32FieldList(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setInt64FieldList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setUint32FieldList(value);
      break;
    case 6:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setUint64FieldList(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setSint32FieldList(value);
      break;
    case 8:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint64());
      msg.setSint64FieldList(value);
      break;
    case 9:
      var value = /** @type {!Array<number>} */ (reader.readPackedFixed32());
      msg.setFixed32FieldList(value);
      break;
    case 10:
      var value = /** @type {!Array<number>} */ (reader.readPackedFixed64());
      msg.setFixed64FieldList(value);
      break;
    case 11:
      var value = /** @type {!Array<number>} */ (reader.readPackedSfixed32());
      msg.setSfixed32FieldList(value);
      break;
    case 12:
      var value = /** @type {!Array<number>} */ (reader.readPackedSfixed64());
      msg.setSfixed64FieldList(value);
      break;
    case 13:
      var value = /** @type {!Array<boolean>} */ (reader.readPackedBool());
      msg.setBoolFieldList(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringField(value);
      break;
    case 15:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addBytesField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDoubleFieldList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getFloatFieldList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
  f = message.getInt32FieldList();
  if (f.length > 0) {
    writer.writePackedInt32(
      3,
      f
    );
  }
  f = message.getInt64FieldList();
  if (f.length > 0) {
    writer.writePackedInt64(
      4,
      f
    );
  }
  f = message.getUint32FieldList();
  if (f.length > 0) {
    writer.writePackedUint32(
      5,
      f
    );
  }
  f = message.getUint64FieldList();
  if (f.length > 0) {
    writer.writePackedUint64(
      6,
      f
    );
  }
  f = message.getSint32FieldList();
  if (f.length > 0) {
    writer.writePackedSint32(
      7,
      f
    );
  }
  f = message.getSint64FieldList();
  if (f.length > 0) {
    writer.writePackedSint64(
      8,
      f
    );
  }
  f = message.getFixed32FieldList();
  if (f.length > 0) {
    writer.writePackedFixed32(
      9,
      f
    );
  }
  f = message.getFixed64FieldList();
  if (f.length > 0) {
    writer.writePackedFixed64(
      10,
      f
    );
  }
  f = message.getSfixed32FieldList();
  if (f.length > 0) {
    writer.writePackedSfixed32(
      11,
      f
    );
  }
  f = message.getSfixed64FieldList();
  if (f.length > 0) {
    writer.writePackedSfixed64(
      12,
      f
    );
  }
  f = message.getBoolFieldList();
  if (f.length > 0) {
    writer.writePackedBool(
      13,
      f
    );
  }
  f = message.getStringFieldList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getBytesFieldList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      15,
      f
    );
  }
};


/**
 * repeated double double_field = 1;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getDoubleFieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setDoubleFieldList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addDoubleField = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearDoubleFieldList = function() {
  this.setDoubleFieldList([]);
};


/**
 * repeated float float_field = 2;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getFloatFieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setFloatFieldList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addFloatField = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearFloatFieldList = function() {
  this.setFloatFieldList([]);
};


/**
 * repeated int32 int32_field = 3;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getInt32FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setInt32FieldList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addInt32Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearInt32FieldList = function() {
  this.setInt32FieldList([]);
};


/**
 * repeated int64 int64_field = 4;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getInt64FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setInt64FieldList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addInt64Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearInt64FieldList = function() {
  this.setInt64FieldList([]);
};


/**
 * repeated uint32 uint32_field = 5;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getUint32FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setUint32FieldList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addUint32Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearUint32FieldList = function() {
  this.setUint32FieldList([]);
};


/**
 * repeated uint64 uint64_field = 6;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getUint64FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setUint64FieldList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addUint64Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearUint64FieldList = function() {
  this.setUint64FieldList([]);
};


/**
 * repeated sint32 sint32_field = 7;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getSint32FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setSint32FieldList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addSint32Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearSint32FieldList = function() {
  this.setSint32FieldList([]);
};


/**
 * repeated sint64 sint64_field = 8;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getSint64FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setSint64FieldList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addSint64Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearSint64FieldList = function() {
  this.setSint64FieldList([]);
};


/**
 * repeated fixed32 fixed32_field = 9;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getFixed32FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setFixed32FieldList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addFixed32Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearFixed32FieldList = function() {
  this.setFixed32FieldList([]);
};


/**
 * repeated fixed64 fixed64_field = 10;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getFixed64FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setFixed64FieldList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addFixed64Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearFixed64FieldList = function() {
  this.setFixed64FieldList([]);
};


/**
 * repeated sfixed32 sfixed32_field = 11;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getSfixed32FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setSfixed32FieldList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addSfixed32Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearSfixed32FieldList = function() {
  this.setSfixed32FieldList([]);
};


/**
 * repeated sfixed64 sfixed64_field = 12;
 * @return {!Array<number>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getSfixed64FieldList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<number>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setSfixed64FieldList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addSfixed64Field = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearSfixed64FieldList = function() {
  this.setSfixed64FieldList([]);
};


/**
 * repeated bool bool_field = 13;
 * @return {!Array<boolean>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getBoolFieldList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedBooleanField(this, 13));
};


/** @param {!Array<boolean>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setBoolFieldList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {boolean} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addBoolField = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearBoolFieldList = function() {
  this.setBoolFieldList([]);
};


/**
 * repeated string string_field = 14;
 * @return {!Array<string>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getStringFieldList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/** @param {!Array<string>} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setStringFieldList = function(value) {
  jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addStringField = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearStringFieldList = function() {
  this.setStringFieldList([]);
};


/**
 * repeated bytes bytes_field = 15;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getBytesFieldList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * repeated bytes bytes_field = 15;
 * This is a type-conversion wrapper around `getBytesFieldList()`
 * @return {!Array<string>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getBytesFieldList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getBytesFieldList()));
};


/**
 * repeated bytes bytes_field = 15;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesFieldList()`
 * @return {!Array<!Uint8Array>}
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.getBytesFieldList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getBytesFieldList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.setBytesFieldList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.addBytesField = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.protoc_gen_es6.tests.proto.RepeatedPrimitiveTest.prototype.clearBytesFieldList = function() {
  this.setBytesFieldList([]);
};


goog.object.extend(exports, proto.protoc_gen_es6.tests.proto);
